import csv
from pathlib import Path


ROOT = Path(r"E:\科研")
REPORT_DIR = ROOT / "超粒球RAG_数据" / "reports"


METHODS = [
    ("tfidf_fixed", "TF-IDF fixed", "stage1_tfidf_summary.csv"),
    ("tfidf_stage1f", "TF-IDF Stage1F gated", "stage1_fg_boundary_size8_score12_summary.csv"),
    ("dense_fixed", "Dense fixed", "stage2_dense_allminilm_fixed_summary.csv"),
    ("dense_ball", "Dense ball-only", "stage2_dense_allminilm_ball_summary.csv"),
    ("dense_facet", "Dense facet", "stage2_dense_allminilm_facet_summary.csv"),
    ("dense_gated", "Dense gated", "stage2_dense_allminilm_gated_summary.csv"),
]


def read_summary(filename: str) -> dict[str, dict[str, str]]:
    with (REPORT_DIR / filename).open("r", encoding="utf-8", newline="") as f:
        return {row["dataset"]: row for row in csv.DictReader(f)}


def val(row: dict[str, str], key: str) -> float:
    if key not in row or row[key] == "":
        return 0.0
    return float(row[key])


def fmt(value: float) -> str:
    return f"{value:.4f}"


def main() -> None:
    summaries = [(method_id, name, filename, read_summary(filename)) for method_id, name, filename in METHODS]
    dense_fixed = summaries[2][3]
    tfidf_fixed = summaries[0][3]
    rows = []
    for method_id, name, filename, summary in summaries:
        for dataset in ["ALL", "hotpotqa", "musique"]:
            row = summary[dataset]
            rows.append(
                {
                    "method_id": method_id,
                    "method": name,
                    "dataset": dataset,
                    "source_file": filename,
                    "er5": fmt(val(row, "evidence_recall_at_5")),
                    "cr5": fmt(val(row, "chain_recall_at_5")),
                    "er10": fmt(val(row, "evidence_recall_at_10")),
                    "cr10": fmt(val(row, "chain_recall_at_10")),
                    "tokens10": fmt(val(row, "context_tokens_at_10")),
                    "hyperedge_rate": fmt(val(row, "hyperedge_rate")),
                    "expansion_yield": fmt(val(row, "expansion_yield")),
                    "false_expansion_rate": fmt(val(row, "false_expansion_rate")),
                    "delta_cr10_vs_dense_fixed": fmt(val(row, "chain_recall_at_10") - val(dense_fixed[dataset], "chain_recall_at_10")),
                    "delta_cr10_vs_tfidf_fixed": fmt(val(row, "chain_recall_at_10") - val(tfidf_fixed[dataset], "chain_recall_at_10")),
                }
            )

    csv_path = REPORT_DIR / "stage2_dense_compare.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    md_path = ROOT / "超粒球RAG_Stage2B_Dense复现实验报告.md"
    lines = [
        "# 超粒球RAG Stage2B Dense 复现实验报告",
        "",
        "## Material Passport",
        "",
        "- Artifact: Stage2B dense embedding replication",
        "- Status: ANALYZED",
        "- Embedding model: sentence-transformers/all-MiniLM-L6-v2 via transformers mean pooling",
        "- Scope: retrieval-only, HotpotQA sample200 + MuSiQue sample200",
        "- Environment note: transformers completed, but runtime printed NumPy/numexpr/sklearn compatibility warnings; results below come from completed output files.",
        "- Generated by: stage2_dense_compare.py",
        "",
        "## ALL 对照",
        "",
        "| Method | ER@5 | CR@5 | ER@10 | CR@10 | ΔCR@10 vs dense fixed | HE rate | Yield | False expansion |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        if row["dataset"] != "ALL":
            continue
        lines.append(
            "| {method} | {er5} | {cr5} | {er10} | {cr10} | {delta_dense} | {he} | {yield_} | {false} |".format(
                method=row["method"],
                er5=row["er5"],
                cr5=row["cr5"],
                er10=row["er10"],
                cr10=row["cr10"],
                delta_dense=row["delta_cr10_vs_dense_fixed"],
                he=row["hyperedge_rate"],
                yield_=row["expansion_yield"],
                false=row["false_expansion_rate"],
            )
        )

    lines.extend(
        [
            "",
            "## 分数据集 Dense 结果",
            "",
            "| Dataset | Method | ER@10 | CR@10 | ΔCR@10 vs dense fixed | False expansion |",
            "|---|---|---:|---:|---:|---:|",
        ]
    )
    for row in rows:
        if row["dataset"] == "ALL":
            continue
        if not row["method_id"].startswith("dense"):
            continue
        lines.append(
            "| {dataset} | {method} | {er10} | {cr10} | {delta_dense} | {false} |".format(
                dataset=row["dataset"],
                method=row["method"],
                er10=row["er10"],
                cr10=row["cr10"],
                delta_dense=row["delta_cr10_vs_dense_fixed"],
                false=row["false_expansion_rate"],
            )
        )

    dense_fixed_all = next(row for row in rows if row["method_id"] == "dense_fixed" and row["dataset"] == "ALL")
    dense_gated_all = next(row for row in rows if row["method_id"] == "dense_gated" and row["dataset"] == "ALL")
    tfidf_stage1f_all = next(row for row in rows if row["method_id"] == "tfidf_stage1f" and row["dataset"] == "ALL")
    lines.extend(
        [
            "",
            "## 证据结论",
            "",
            f"- Dense fixed baseline 很强：ALL CR@10 = {dense_fixed_all['cr10']}，明显高于 TF-IDF Stage1F 的 {tfidf_stage1f_all['cr10']}。",
            f"- Dense gated 当前不是有效改进：ALL CR@10 = {dense_gated_all['cr10']}，比 dense fixed 低 {dense_gated_all['delta_cr10_vs_dense_fixed']}。",
            "- Dense facet/gated 的 false expansion 仍高，且扩展后 Top-10 链路召回下降，说明 TF-IDF 空间中的粒球/超边参数不能直接迁移到 dense embedding 空间。",
            "- 当前应保留 TF-IDF Stage1F 作为已验证主线，同时把 dense 结果作为边界条件：方法需要向量空间自适应的粒球半径、seed 选择和扩展门控。",
            "",
            "## 下一步建议",
            "",
            "1. 不要用当前 dense gated 声称泛化成功。",
            "2. 做 dense 参数重标定：扫描 radius_threshold、seed_balls、max_size、decision_min_ball_score。",
            "3. 引入 dense fixed reranking 保护：超边扩展只能补充候选，不应替换 dense fixed Top-10 的高置信单位。",
            "4. 对 dense ball-only 失败做结构分析：当前 Top-20 平均只返回 7.92 个 ball units，粒球截断过强。",
            "",
            f"CSV output: `{csv_path}`",
        ]
    )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
