import csv
from pathlib import Path


ROOT = Path(r"E:\SCIENCE")
REPORT_DIR = ROOT / "超粒球RAG_数据" / "reports"


METHODS = [
    ("stage1e", "Stage1E facet-aware e2/b2", "stage1_facet_fill_e2_b2_s010_summary.csv"),
    ("stage1f_best", "Stage1F best boundary size8 score12", "stage1_fg_boundary_size8_score12_summary.csv"),
    ("gp_nonew025", "Stage1H allow no-new if score >= 0.25", "stage1_fg_gp_nonew025_summary.csv"),
    ("gp_nonew020", "Stage1H allow no-new if score >= 0.20", "stage1_fg_gp_nonew020_summary.csv"),
    ("gp_size12", "Stage1H max candidate size 12", "stage1_fg_gp_size12_summary.csv"),
]


def read_summary(filename: str) -> dict[str, dict[str, str]]:
    with (REPORT_DIR / filename).open("r", encoding="utf-8", newline="") as f:
        return {row["dataset"]: row for row in csv.DictReader(f)}


def val(row: dict[str, str], key: str) -> float:
    if key not in row or row[key] == "":
        return 0.0
    return float(row[key])


def fmt(value: float) -> str:
    return f"{value:.4f}"


def main() -> None:
    summaries = [(method_id, name, filename, read_summary(filename)) for method_id, name, filename in METHODS]
    f_best = summaries[1][3]
    rows = []
    for method_id, name, filename, summary in summaries:
        for dataset in ["ALL", "hotpotqa", "musique"]:
            row = summary[dataset]
            best = f_best[dataset]
            rows.append(
                {
                    "method_id": method_id,
                    "method": name,
                    "dataset": dataset,
                    "source_file": filename,
                    "hyperedge_rate": fmt(val(row, "hyperedge_rate")),
                    "avg_selected_edges": fmt(val(row, "avg_selected_edges")),
                    "expansion_yield": fmt(val(row, "expansion_yield")),
                    "false_expansion_rate": fmt(val(row, "false_expansion_rate")),
                    "evidence_recall_at_10": fmt(val(row, "evidence_recall_at_10")),
                    "chain_recall_at_10": fmt(val(row, "chain_recall_at_10")),
                    "delta_false_vs_stage1f": fmt(val(row, "false_expansion_rate") - val(best, "false_expansion_rate")),
                    "delta_cr10_vs_stage1f": fmt(val(row, "chain_recall_at_10") - val(best, "chain_recall_at_10")),
                }
            )

    csv_path = REPORT_DIR / "stage1_gold_preserve_compare.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    md_path = ROOT / "超粒球RAG_Stage1H保金门控初探.md"
    lines = [
        "# 超粒球RAG Stage1H 保金门控初探",
        "",
        "## Material Passport",
        "",
        "- Artifact: Stage1H gold-preserving proxy scan",
        "- Status: ANALYZED",
        "- Baseline: Stage1F boundary-only size8 score12",
        "- Goal: test whether simple relaxed gates recover gold-bearing expansion without restoring noise",
        "- Generated by: stage1_gold_preserve_compare.py",
        "",
        "## ALL 汇总",
        "",
        "| 方法 | HE率 | Avg edges | Yield | False扩展率 | ER@10 | CR@10 | ΔFalse vs Stage1F | ΔCR@10 vs Stage1F |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        if row["dataset"] != "ALL":
            continue
        lines.append(
            "| {method} | {he} | {edges} | {yield_} | {false} | {er10} | {cr10} | {df} | {dc} |".format(
                method=row["method"],
                he=row["hyperedge_rate"],
                edges=row["avg_selected_edges"],
                yield_=row["expansion_yield"],
                false=row["false_expansion_rate"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                df=row["delta_false_vs_stage1f"],
                dc=row["delta_cr10_vs_stage1f"],
            )
        )

    lines.extend(
        [
            "",
            "## 分数据集",
            "",
            "| 数据集 | 方法 | False扩展率 | ER@10 | CR@10 | ΔFalse vs Stage1F | ΔCR@10 vs Stage1F |",
            "|---|---|---:|---:|---:|---:|---:|",
        ]
    )
    for row in rows:
        if row["dataset"] == "ALL":
            continue
        if row["method_id"] not in {"stage1f_best", "gp_nonew025", "gp_nonew020", "gp_size12"}:
            continue
        lines.append(
            "| {dataset} | {method} | {false} | {er10} | {cr10} | {df} | {dc} |".format(
                dataset=row["dataset"],
                method=row["method"],
                false=row["false_expansion_rate"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                df=row["delta_false_vs_stage1f"],
                dc=row["delta_cr10_vs_stage1f"],
            )
        )

    lines.extend(
        [
            "",
            "## 证据结论",
            "",
            "- `allow-high-score-no-new` 在 score >= 0.25 和 score >= 0.20 两组下，ALL ER@10/CR@10/false_expansion_rate 与 Stage1F best 完全一致；当前 top_facet_edges/max_expanded_balls 预算下，这类候选没有进入最终 selected edges。",
            "- 放宽 `max_candidate_ball_size` 到 12 会使 ALL false_expansion_rate 从 0.8336 升到 0.8405，CR@10 从 0.3725 降到 0.3675。",
            "- 因此，简单放宽门控不是有效的 gold-preserving 策略；下一步需要更细的替换策略，例如只在会补足缺失 query facet 或提高 top-k 排序稳定性时放行。",
            "",
            f"CSV output: `{csv_path}`",
        ]
    )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
