import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean
from typing import Any


ROOT = Path(r"E:\SCIENCE")
PROCESSED_DIR = ROOT / "超粒球RAG_数据" / "processed"
REPORT_DIR = ROOT / "超粒球RAG_数据" / "reports"

REJECTED_PATH = PROCESSED_DIR / "stage1_fg_boundary_size8_score12_rejected_edges.jsonl"
CSV_PATH = REPORT_DIR / "stage1_gate_reject_audit.csv"
MD_PATH = ROOT / "超粒球RAG_Stage1G拒绝原因审计.md"


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def num(row: dict[str, Any], key: str) -> float:
    value = row.get(key)
    if value is None or value == "":
        return 0.0
    return float(value)


def avg(rows: list[dict[str, Any]], key: str) -> float:
    values = [num(row, key) for row in rows if key in row]
    return mean(values) if values else 0.0


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "candidates": len(rows),
        "gold_candidates": sum(1 for row in rows if int(row.get("gold_units", 0)) > 0),
        "zero_gold_candidates": sum(1 for row in rows if int(row.get("gold_units", 0)) == 0),
        "gold_units": sum(int(row.get("gold_units", 0)) for row in rows),
        "avg_ball_score": avg(rows, "ball_score"),
        "avg_facet_score": avg(rows, "facet_score"),
        "avg_ball_size": avg(rows, "ball_size"),
        "avg_units_per_new_term": avg(rows, "units_per_new_term"),
        "avg_max_seed_similarity": avg(rows, "max_seed_similarity"),
        "avg_redundancy": avg(rows, "redundancy"),
        "avg_new_terms": mean([len(row.get("new_terms", [])) for row in rows]) if rows else 0.0,
    }


def fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def main() -> None:
    rejected = read_jsonl(REJECTED_PATH)
    for row in rejected:
        row["gold_class"] = "gold" if int(row.get("gold_units", 0)) > 0 else "zero_gold"

    groups: dict[tuple[str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for row in rejected:
        dataset = row.get("dataset") or "unknown"
        reason = row.get("reject_reason", "unknown")
        gold_class = row["gold_class"]
        groups[(dataset, reason, gold_class)].append(row)
        groups[(dataset, reason, "ALL")].append(row)
        groups[(dataset, "ALL", gold_class)].append(row)
        groups[(dataset, "ALL", "ALL")].append(row)
        groups[("ALL", reason, gold_class)].append(row)
        groups[("ALL", reason, "ALL")].append(row)
        groups[("ALL", "ALL", gold_class)].append(row)
        groups[("ALL", "ALL", "ALL")].append(row)

    rows: list[dict[str, Any]] = []
    for key in sorted(groups):
        dataset, reason, gold_class = key
        summary = summarize(groups[key])
        rows.append({"dataset": dataset, "reject_reason": reason, "gold_class": gold_class, **summary})

    with CSV_PATH.open("w", encoding="utf-8", newline="") as f_csv:
        writer = csv.DictWriter(f_csv, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    counts = Counter((row.get("reject_reason", "unknown"), row["gold_class"]) for row in rejected)
    all_by_reason = {reason: summarize([row for row in rejected if row.get("reject_reason") == reason]) for reason in sorted({row.get("reject_reason") for row in rejected})}
    gold_by_reason = {
        reason: summarize([row for row in rejected if row.get("reject_reason") == reason and int(row.get("gold_units", 0)) > 0])
        for reason in sorted({row.get("reject_reason") for row in rejected})
    }

    lines = [
        "# 超粒球RAG Stage1G 拒绝原因审计",
        "",
        "## Material Passport",
        "",
        "- Artifact: Stage1G reject-reason audit",
        "- Status: ANALYZED",
        "- Source: Stage1F boundary-only size8 score12 rejected-edge log",
        "- Unit of analysis: rejected candidate granular ball",
        "- Generated by: stage1_gate_reject_audit.py",
        "",
        "## ALL 拒绝原因",
        "",
        "| reason | candidates | zero-gold | gold candidates | gold units | avg ball score | avg facet score | avg size | avg units/new |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for reason, summary in all_by_reason.items():
        lines.append(
            "| {reason} | {candidates} | {zero} | {gold} | {gold_units} | {ball_score} | {facet_score} | {size} | {units_per_new} |".format(
                reason=reason,
                candidates=summary["candidates"],
                zero=summary["zero_gold_candidates"],
                gold=summary["gold_candidates"],
                gold_units=summary["gold_units"],
                ball_score=fmt(summary["avg_ball_score"]),
                facet_score=fmt(summary["avg_facet_score"]),
                size=fmt(summary["avg_ball_size"]),
                units_per_new=fmt(summary["avg_units_per_new_term"]),
            )
        )

    lines.extend(
        [
            "",
            "## Gold-bearing rejected candidates",
            "",
            "| reason | gold candidates | gold units | avg ball score | avg facet score | avg size | avg units/new | avg seed sim | avg redundancy |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for reason, summary in gold_by_reason.items():
        if summary["candidates"] == 0:
            continue
        lines.append(
            "| {reason} | {candidates} | {gold_units} | {ball_score} | {facet_score} | {size} | {units_per_new} | {seed_sim} | {redundancy} |".format(
                reason=reason,
                candidates=summary["candidates"],
                gold_units=summary["gold_units"],
                ball_score=fmt(summary["avg_ball_score"]),
                facet_score=fmt(summary["avg_facet_score"]),
                size=fmt(summary["avg_ball_size"]),
                units_per_new=fmt(summary["avg_units_per_new_term"]),
                seed_sim=fmt(summary["avg_max_seed_similarity"]),
                redundancy=fmt(summary["avg_redundancy"]),
            )
        )

    all_summary = summarize(rejected)
    gold_summary = summarize([row for row in rejected if int(row.get("gold_units", 0)) > 0])
    lines.extend(
        [
            "",
            "## 证据解读",
            "",
            f"- rejected candidates 总数 {all_summary['candidates']}，其中 gold-bearing candidates {gold_summary['candidates']}，包含 gold units {gold_summary['gold_units']}。",
            f"- gold-bearing rejected candidates 的 avg ball_score = {gold_summary['avg_ball_score']:.4f}；这说明部分被拒候选与 query/seed 仍有较强锚定。",
            "- 如果后续做 Stage1H，优先测试 gold-preserving proxy：对高 ball_score 或高 seed similarity 的候选放宽 size/ratio gate，而不是继续降低全局阈值。",
            "",
            f"CSV output: `{CSV_PATH}`",
        ]
    )
    MD_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {CSV_PATH}")
    print(f"Wrote {MD_PATH}")
    print("Reject counts:", {str(key): value for key, value in counts.items()})


if __name__ == "__main__":
    main()
