import csv
from pathlib import Path


ROOT = Path(r"E:\科研")
REPORT_DIR = ROOT / "超粒球RAG_数据" / "reports"


METHODS = [
    ("fixed_tfidf", "Fixed TF-IDF sentence unit", "stage1_tfidf_summary.csv"),
    ("gb_only", "Adaptive granular ball only", "stage1_granular_ball_summary.csv"),
    ("boundary_fallback", "Boundary fallback granular ball", "stage1_bf_b050_s010_m020_summary.csv"),
    ("naive_hyperedge", "Unsupervised hyperedge expansion", "stage1_he_kw4_sim045_seed2_summary.csv"),
    ("query_aware_hyperedge", "Query-aware hyperedge expansion", "stage1_qa_fill_e4_b4_t020_summary.csv"),
    ("facet_aware_hyperedge", "Facet-aware hyperedge expansion", "stage1_facet_fill_e2_b2_s010_summary.csv"),
    ("facet_aware_larger_budget", "Facet-aware hyperedge expansion, larger budget", "stage1_facet_fill_e4_b4_s010_summary.csv"),
]


METRICS = [
    "avg_mrr",
    "boundary_rate",
    "hyperedge_rate",
    "avg_selected_edges",
    "avg_expanded_balls",
    "facet_gain",
    "expansion_yield",
    "false_expansion_rate",
    "evidence_recall_at_5",
    "chain_recall_at_5",
    "context_tokens_at_5",
    "evidence_recall_at_10",
    "chain_recall_at_10",
    "context_tokens_at_10",
]


def read_summary(path):
    with path.open("r", encoding="utf-8", newline="") as f:
        return {row["dataset"]: row for row in csv.DictReader(f)}


def fnum(row, key):
    value = row.get(key, "")
    if value == "":
        return None
    return float(value)


def fmt(value, digits=4):
    if value is None:
        return ""
    return f"{value:.{digits}f}"


def metric(row, key):
    return fnum(row, key) if key in row and row[key] != "" else None


def main():
    rows = []
    summaries = []
    for method_id, method_name, filename in METHODS:
        path = REPORT_DIR / filename
        if not path.exists():
            raise FileNotFoundError(path)
        summaries.append((method_id, method_name, filename, read_summary(path)))

    baseline = summaries[0][3]
    for method_id, method_name, filename, summary in summaries:
        for dataset in ["ALL", "hotpotqa", "musique"]:
            row = summary[dataset]
            base = baseline[dataset]
            out = {
                "method_id": method_id,
                "method": method_name,
                "source_file": filename,
                "dataset": dataset,
                "queries": row.get("queries", ""),
            }
            for key in METRICS:
                out[key] = fmt(metric(row, key))
            for key in [
                "evidence_recall_at_5",
                "chain_recall_at_5",
                "evidence_recall_at_10",
                "chain_recall_at_10",
            ]:
                value = metric(row, key)
                base_value = metric(base, key)
                out[f"delta_{key}_vs_tfidf"] = fmt(value - base_value if value is not None and base_value is not None else None)
            rows.append(out)

    csv_path = REPORT_DIR / "stage1_consolidated_ablation.csv"
    fieldnames = list(rows[0].keys())
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    md_path = ROOT / "超粒球RAG_Stage1总消融表.md"
    lines = []
    lines.append("# 超粒球RAG Stage1 总消融表")
    lines.append("")
    lines.append("## Material Passport")
    lines.append("")
    lines.append("- Artifact: Stage1 consolidated ablation table")
    lines.append("- Status: ANALYZED")
    lines.append("- Input: HotpotQA sample200 + MuSiQue sample200 retrieval-only results")
    lines.append("- Scope: fixed sentence TF-IDF, adaptive granular ball, boundary fallback, hyperedge variants")
    lines.append("- Generated by: stage1_consolidate_ablation.py")
    lines.append("")
    lines.append("## ALL 数据集汇总")
    lines.append("")
    lines.append("| 方法 | ER@5 | CR@5 | ER@10 | CR@10 | Tok@10 | HE率 | 扩展收益 | 错扩率 | CR@10较TF-IDF |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in rows:
        if row["dataset"] != "ALL":
            continue
        lines.append(
            "| {method} | {er5} | {cr5} | {er10} | {cr10} | {tok10} | {he} | {yield_} | {false} | {dcr10} |".format(
                method=row["method"],
                er5=row["evidence_recall_at_5"],
                cr5=row["chain_recall_at_5"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                tok10=row["context_tokens_at_10"],
                he=row["hyperedge_rate"],
                yield_=row["expansion_yield"],
                false=row["false_expansion_rate"],
                dcr10=row["delta_chain_recall_at_10_vs_tfidf"],
            )
        )

    lines.append("")
    lines.append("## 分数据集关键表")
    lines.append("")
    lines.append("| 数据集 | 方法 | ER@5 | CR@5 | ER@10 | CR@10 | Tok@10 | CR@10较TF-IDF |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|")
    for row in rows:
        if row["dataset"] == "ALL":
            continue
        lines.append(
            "| {dataset} | {method} | {er5} | {cr5} | {er10} | {cr10} | {tok10} | {dcr10} |".format(
                dataset=row["dataset"],
                method=row["method"],
                er5=row["evidence_recall_at_5"],
                cr5=row["chain_recall_at_5"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                tok10=row["context_tokens_at_10"],
                dcr10=row["delta_chain_recall_at_10_vs_tfidf"],
            )
        )

    lines.append("")
    lines.append("## 直接证据")
    lines.append("")
    lines.append("- Fixed TF-IDF: ALL CR@10 = 0.3125, ER@10 = 0.6187。")
    lines.append("- Boundary fallback: ALL CR@10 = 0.3200，接近 TF-IDF，但 fallback_rate = 0.9175，说明收益主要来自边界回退策略。")
    lines.append("- Unsupervised hyperedge: ALL CR@10 = 0.3700，ER@10 = 0.6410，但 false_expansion_rate = 0.9456，噪声很高。")
    lines.append("- Query-aware hyperedge: ALL CR@10 = 0.3225，未明显超过无监督超边，说明仅靠 query-aware 重排不足。")
    lines.append("- Facet-aware hyperedge: ALL CR@10 = 0.3725，MuSiQue CR@10 = 0.4150，false_expansion_rate = 0.8560，是当前较稳的机制证据。")
    lines.append("- Facet-aware larger budget: ALL CR@5 = 0.2000，ER@5 = 0.4874，但 CR@10 = 0.3600，较 e2/b2 配置稍低。")
    lines.append("")
    lines.append("## 当前结论边界")
    lines.append("")
    lines.append("- 可支持的说法：Facet-aware 超边在多跳链路召回上优于固定句子 TF-IDF，尤其 MuSiQue 的 CR@10 从 0.2950 到 0.4150。")
    lines.append("- 不能支持的说法：粒球本身天然优于 fixed chunk；Stage1 中 naive granular ball 的 ALL CR@10 只有 0.2950。")
    lines.append("- 仍需解决：超边扩展的 false_expansion_rate 仍高于 0.85，下一步应定位改进/退化样例，而不是继续盲目加预算。")
    lines.append("")
    lines.append(f"CSV output: `{csv_path}`")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
