import csv
from pathlib import Path


ROOT = Path(r"E:\科研")
REPORT_DIR = ROOT / "超粒球RAG_数据" / "reports"


METHODS = [
    ("fixed_tfidf", "Fixed TF-IDF", "stage1_tfidf_summary.csv"),
    ("facet_e2_b2", "Stage1E facet-aware e2/b2", "stage1_facet_fill_e2_b2_s010_summary.csv"),
    ("fg_size8_score08", "Stage1F gated size8 score08", "stage1_fg_size8_score08_summary.csv"),
    ("fg_size5_score08", "Stage1F gated size5 score08", "stage1_fg_size5_score08_summary.csv"),
    ("fg_size8_score12", "Stage1F gated size8 score12", "stage1_fg_size8_score12_summary.csv"),
    ("fg_boundary_size8_score08", "Stage1F boundary-only size8 score08", "stage1_fg_boundary_size8_score08_summary.csv"),
    ("fg_boundary_size5_score08", "Stage1F boundary-only size5 score08", "stage1_fg_boundary_size5_score08_summary.csv"),
    ("fg_boundary_size8_score12", "Stage1F boundary-only size8 score12", "stage1_fg_boundary_size8_score12_summary.csv"),
    ("fg_boundary_size8_ratio4", "Stage1F boundary-only size8 ratio4", "stage1_fg_boundary_size8_ratio4_summary.csv"),
]


def read_summary(filename: str) -> dict[str, dict[str, str]]:
    path = REPORT_DIR / filename
    if not path.exists():
        raise FileNotFoundError(path)
    with path.open("r", encoding="utf-8", newline="") as f:
        return {row["dataset"]: row for row in csv.DictReader(f)}


def val(row: dict[str, str], key: str) -> float | None:
    if key not in row or row[key] == "":
        return None
    return float(row[key])


def fmt(value: float | None, digits: int = 4) -> str:
    if value is None:
        return ""
    return f"{value:.{digits}f}"


def main() -> None:
    summaries = [(method_id, name, filename, read_summary(filename)) for method_id, name, filename in METHODS]
    tfidf = summaries[0][3]
    stage1e = summaries[1][3]

    rows: list[dict[str, str]] = []
    for method_id, name, filename, summary in summaries:
        for dataset in ["ALL", "hotpotqa", "musique"]:
            row = summary[dataset]
            er10 = val(row, "evidence_recall_at_10")
            cr10 = val(row, "chain_recall_at_10")
            false_rate = val(row, "false_expansion_rate")
            base_cr10 = val(tfidf[dataset], "chain_recall_at_10")
            e_cr10 = val(stage1e[dataset], "chain_recall_at_10")
            e_false = val(stage1e[dataset], "false_expansion_rate")
            rows.append(
                {
                    "method_id": method_id,
                    "method": name,
                    "dataset": dataset,
                    "source_file": filename,
                    "hyperedge_rate": fmt(val(row, "hyperedge_rate")),
                    "avg_selected_edges": fmt(val(row, "avg_selected_edges")),
                    "expansion_yield": fmt(val(row, "expansion_yield")),
                    "false_expansion_rate": fmt(false_rate),
                    "evidence_recall_at_5": fmt(val(row, "evidence_recall_at_5")),
                    "chain_recall_at_5": fmt(val(row, "chain_recall_at_5")),
                    "evidence_recall_at_10": fmt(er10),
                    "chain_recall_at_10": fmt(cr10),
                    "delta_cr10_vs_tfidf": fmt(cr10 - base_cr10 if cr10 is not None and base_cr10 is not None else None),
                    "delta_cr10_vs_stage1e": fmt(cr10 - e_cr10 if cr10 is not None and e_cr10 is not None else None),
                    "delta_false_vs_stage1e": fmt(false_rate - e_false if false_rate is not None and e_false is not None else None),
                }
            )

    csv_path = REPORT_DIR / "stage1_noise_gate_compare.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    md_path = ROOT / "超粒球RAG_Stage1F噪声门控报告.md"
    lines = [
        "# 超粒球RAG Stage1F 噪声门控报告",
        "",
        "## Material Passport",
        "",
        "- Artifact: Stage1F noise-gate comparison",
        "- Status: ANALYZED",
        "- Input: HotpotQA sample200 + MuSiQue sample200 retrieval-only results",
        "- Compared baseline: fixed TF-IDF and Stage1E facet-aware e2/b2/s010",
        "- Generated by: stage1_noise_gate_compare.py",
        "",
        "## ALL 汇总",
        "",
        "| 方法 | HE率 | Avg edges | Yield | False扩展率 | ER@5 | CR@5 | ER@10 | CR@10 | ΔCR@10 vs TF-IDF | ΔCR@10 vs Stage1E | ΔFalse vs Stage1E |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        if row["dataset"] != "ALL":
            continue
        lines.append(
            "| {method} | {he} | {edges} | {yield_} | {false} | {er5} | {cr5} | {er10} | {cr10} | {dt} | {de} | {df} |".format(
                method=row["method"],
                he=row["hyperedge_rate"],
                edges=row["avg_selected_edges"],
                yield_=row["expansion_yield"],
                false=row["false_expansion_rate"],
                er5=row["evidence_recall_at_5"],
                cr5=row["chain_recall_at_5"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                dt=row["delta_cr10_vs_tfidf"],
                de=row["delta_cr10_vs_stage1e"],
                df=row["delta_false_vs_stage1e"],
            )
        )
    lines.extend(
        [
            "",
            "## 分数据集关键结果",
            "",
            "| 数据集 | 方法 | False扩展率 | ER@10 | CR@10 | ΔCR@10 vs Stage1E | ΔFalse vs Stage1E |",
            "|---|---|---:|---:|---:|---:|---:|",
        ]
    )
    for row in rows:
        if row["dataset"] == "ALL":
            continue
        if row["method_id"] not in {"facet_e2_b2", "fg_boundary_size8_score12", "fg_boundary_size5_score08", "fg_boundary_size8_ratio4"}:
            continue
        lines.append(
            "| {dataset} | {method} | {false} | {er10} | {cr10} | {de} | {df} |".format(
                dataset=row["dataset"],
                method=row["method"],
                false=row["false_expansion_rate"],
                er10=row["evidence_recall_at_10"],
                cr10=row["chain_recall_at_10"],
                de=row["delta_cr10_vs_stage1e"],
                df=row["delta_false_vs_stage1e"],
            )
        )
    lines.extend(
        [
            "",
            "## 证据结论",
            "",
            "- Stage1F boundary-only size8 score12 在 ALL 上保持 Stage1E 的 CR@10 = 0.3725，同时 false_expansion_rate 从 0.8560 降到 0.8336。",
            "- 该配置在 MuSiQue 上保持 CR@10 = 0.4150，并将 false_expansion_rate 从 0.8550 降到 0.8415。",
            "- 更严格的 size5 或 ratio4 能继续降低 false_expansion_rate 到约 0.8296，但 ALL CR@10 分别下降到 0.3625 和 0.3700。",
            "- 因此当前最合理主线不是扩大超边预算，而是保留 boundary uncertainty 触发，再用轻量噪声门控筛掉大而弱锚定的扩展球。",
            "",
            "## 当前可写入论文的方法表述",
            "",
            "在检索阶段，系统首先使用自适应粒球形成局部知识单元；随后用边界不确定性判定是否需要跨粒球扩展；若触发扩展，仅接受同时满足 query facet 覆盖、球大小、query/seed 锚定和单位-新增facet比例约束的候选超边。该策略在不使用答案标签构建索引的条件下，降低了超边噪声并保持多跳链路召回。",
            "",
            f"CSV output: `{csv_path}`",
        ]
    )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
